pipeline {
    agent any 
    
    stages { 
        stage('SCM Checkout') {
            steps {
                retry(3) {
                    git branch: 'main', url: 'https://github.com/PraveenAththanayake/Ecommerce_System'
                }
            }
        }
        stage('Build Docker Image') {
            steps {  
                bat 'docker build -t praveenaththanayake/estore-client:%BUILD_NUMBER% -f client/Dockerfile client'
            }
        }
        stage('Install Dependencies') {
            steps {
                script {
                    bat 'docker run --rm praveenaththanayake/estore-client:%BUILD_NUMBER% npm install'
                }
            }
        }
        stage('Login to Docker Hub') {
            steps {
                withCredentials([string(credentialsId: 'estore', variable: 'estore')]) {
                    script {
                        bat "docker login -u praveenaththanayake -p %estore%"
                    }
                }
            }
        }
        stage('Push Image') {
            steps {
                bat 'docker push praveenaththanayake/estore-client:%BUILD_NUMBER%'
            }
        }
        stage('Deploy with Docker Compose') {
            steps {
                script {
                    echo 'Deploying application with Docker Compose...'
                    bat '''
                        cd client
                        cd
                        docker-compose down
                        docker-compose up -d --build
                    '''
                }
            }
        }
    }
    post {
        always {
            bat 'docker logout'
        }
        success {
            echo 'Pipeline executed successfully!'
        }
        failure {
            echo 'Pipeline execution failed. Check logs for details.'
        }
    }
} 