services:
  app:
    image: praveenaththanayake/estore-server:${BUILD_NUMBER}
    ports:
      - "3000:3000"
    volumes:
      - ./:/usr/src/app # This will now correctly mount the server directory
    environment:
      NODE_ENV: production
