version: "3.8"
services:
  app:
    image: praveenaththanayake/estore-server:${BUILD_NUMBER}
    ports:
      - "3000:3000"
    volumes:
      - .:/usr/src/app
    environment:
      NODE_ENV: production
